version: '3'  
services:  
  pikpaktestsecret:  
    image: kxhubs/pikpaktestsecret  
    ports:  
      - "8080:80"  
    deploy:  
      mode: replicated  
      replicas: 1  
      restart_policy:  
        condition: on-failure
